---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check if teleport is installed.
  command: "/usr/local/bin/teleport version"
  changed_when: False
  register: teleport_version_check
  failed_when: false

- name: Install make.
  package:
    name: make
    state: present

- name: Unarchive teleport.
  unarchive:
    src: "https://get.gravitational.com/teleport-v{{ teleport_version }}-linux-amd64-bin.tar.gz"
    dest: /tmp
    remote_src: yes
  when: "teleport_version_check.rc >= 1 or (teleport_version not in teleport_version_check.stdout)"

- name: Install teleport.
  command: >
    ./install
    chdir=/tmp/teleport
  become: yes
  when: "teleport_version_check.rc >= 1 or (teleport_version not in teleport_version_check.stdout)"

- name: Create teleport config.
  template:
    src: "teleport.yaml.j2"
    dest: "{{ teleport_config_path }}"
    owner: "root"
    group: "root"
    mode: 0600

- include_tasks: configure-Systemd.yml
  when: ansible_service_mgr == 'systemd'

- include_tasks: configure-Upstart.yml
  when: ansible_service_mgr == 'upstart'

- include_tasks: configure-Sysvinit.yml
  when: ansible_service_mgr == 'sysvinit'

- name: Ensure teleport has selected state and enabled on boot.
  service:
    name: 'teleport'
    state: 'reloaded'
    enabled: yes
