---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check if teleport is installed.
  stat: "path=/usr/local/bin/teleport"
  register: teleport_bin

- name: Install make.
  package: name=make state=present

- name: Download teleport installer.
  get_url:
    url: "https://github.com/gravitational/teleport/releases/download/v{{ teleport_version }}/teleport-v{{ teleport_version }}-linux-amd64-bin.tar.gz"
    dest: "/tmp/teleport-v{{ teleport_version }}-linux-amd64-bin.tar.gz"
    mode: 0755
  when: not teleport_bin.stat.exists

- name: Unarchive teleport.
  command: >
    tar -xzvf teleport-v{{ teleport_version }}-linux-amd64-bin.tar.gz
    chdir=/tmp
  when: not teleport_bin.stat.exists

- name: Install teleport.
  command: >
    make install
    chdir=/tmp/teleport
  become: yes
  when: not teleport_bin.stat.exists

- name: Create teleport config.
  template:
    src: "teleport.yaml.j2"
    dest: "{{ teleport_config_path }}"
    owner: "root"
    group: "root"
    mode: 0600

- include: configure-Systemd.yml
  when: ansible_service_mgr == 'systemd'

- include: configure-Upstart.yml
  when: ansible_service_mgr == 'upstart'
  
- include: configure-Sysvinit.yml
  when: ansible_service_mgr == 'sysvinit'

- name: Ensure teleport has selected state and enabled on boot.
  service:
    name: 'teleport'
    state: 'started'
    enabled: yes